---
{{- include "containerssh.configMap" . }}
---
{{- include "containerssh.role" . }}
---
{{- include "containerssh.guestNetworkPolicy" . }}
---
{{- include "containerssh.hostkeySecret" . }}
---
{{- include "containerssh.serviceAccount" . }}
---
{{- include "containerssh.roleBinding" . }}
---
{{- include "containerssh.deployment" . }}
---
{{- include "containerssh.service" . }}